print ("@@@@  @@@@  @@@@  @@@@  @  @")
print ("@     @  @  @     @  @  @  @")
print ("@ @@  @@@@  @ @@  @@@@  @@@@")
print ("@@@@  @  @  @@@@  @  @  @  @")
print ("i'm playing genshin")
print ('how', '"aku main valorant"' )